server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/itom?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  thymeleaf:
    cache: false
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password: root
    jedis:
      pool:
        max-idle: 8
        max-wait: -1
        min-idle: 0
    timeout: 5000
